using CsvHelper.Configuration;
namespace UserDataApi.Models;

/// <summary>
/// Class to facilitate mapping a UserData object from a CSV file.
/// Id is ignored because it will be auto-generated by the database.
/// </summary>
public sealed class UserDataMap : ClassMap<UserData>
{
    public UserDataMap()
    {
        Map(m => m.FirstName);
        Map(m => m.LastName);
        Map(m => m.JobTitle);
        Map(m => m.Phone);
        Map(m => m.Email);

        // Ignore Id so CsvHelper doesn't expect it
        Map(m => m.Id).Ignore();
    }
}

